version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_host
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: user_info
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - 3307:3306
      #ローカルPCからはポート3307で接続できる
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      #初期データ

volumes:
  mysql-volume:
